"""add created_date to venue and artist tables

Revision ID: d874e62da5d4
Revises: 88a8f29c45b1
Create Date: 2024-06-02 22:54:30.173146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd874e62da5d4'
down_revision = '88a8f29c45b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
